# Generated by Django 5.1.7 on 2025-03-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('SPORTS', 'Sports Car'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], default='SEDAN', max_length=20),
        ),
    ]
