# Generated by Django 5.1.7 on 2025-03-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_add_type_field_manually'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SPORTS', '跑车'), ('SUV', 'SUV'), ('SEDAN', '轿车'), ('HATCHBACK', '掀背车')], default='SEDAN', max_length=20, verbose_name='车型'),
        ),
    ]
